name: better_linter
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_code_metrics: ^5.5.1
  very_good_analysis: 4.0.0+1
