name: better_linter
description: A starting point for Dart libraries or applications.
version: 3.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  dart_code_linter: 3.1.1
  very_good_analysis: 10.0.0
