name: better_linter
description: A starting point for Dart libraries or applications.
version: 2.0.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dart_code_linter: 1.1.3
  very_good_analysis: 5.1.0
