name: better_linter
description: A starting point for Dart libraries or applications.
version: 2.0.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dart_code_metrics: 5.7.5
  very_good_analysis: 5.0.0+1
